### ISSUE TITLE
New Topic and Major Update labels are not being displayed as the type

### ISSUE THREAD

**Issue by dshevtsov** [dshevtsov/whats-new-on-devdocs-from#15]
Reported by @erikmarr
It appears that New Topic and Major Update labels are being queried, but those values are not being displayed as the `type:` in the generated yml.
```
- description: Added a 'Declaring the new custom no-route processor' section to the
    [Routing](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/routing.html).
  versions: 2.3.x
  type: 
  date: March 23, 2020
  link: https://github.com/magento/devdocs/pull/6868
```
